use_frameworks!

target 'PPPreCompiledFramework_Example' do
  pod 'PPPreCompiledFramework', :path => '../'

  target 'PPPreCompiledFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
